name: Test Python

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Install dev dependencies
        run: uv sync --extra dev
      # - name: Build package
      #   run: python -m build
      - name: Run unit tests
        run: uv run pytest